name: Release Package

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ windows-latest, macos-latest, ubuntu-latest ]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache-workspaces: |
            ./rust
            ./build/rust_lib_spacehub/build
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - name: Install linux deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
        if: matrix.platform == 'ubuntu-latest'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.x
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Build APKs
        run: flutter build apk --split-per-abi
        if: matrix.platform == 'ubuntu-latest'
      - name: Build Linux
        run: flutter build linux
        if: matrix.platform == 'ubuntu-latest'
      - name: Gzip Linux build
        run: tar -czf ./Linux.tar.gz -C ./build/linux/x64/release/bundle/ .
        if: matrix.platform == 'ubuntu-latest'
      - name: Build Windows
        run: flutter build windows
        if: matrix.platform == 'windows-latest'
      - name: Zip Windows build
        run: Compress-Archive -Path ./build/windows/x64/runner/Release/ -DestinationPath ./Windows.zip
        if: matrix.platform == 'windows-latest'
      - name: Build iOS
        run: flutter build ipa --release --no-codesign
        if: matrix.platform == 'macos-latest'
      - name: Gzip iOS build
        run: tar -czf ./iOS.xcarchive.tar.gz -C ./build/ios/archive/Runner.xcarchive .
        if: matrix.platform == 'macos-latest'
      - name: Build macOS
        run: flutter build macos
        if: matrix.platform == 'macos-latest'
      - name: Gzip macOS build
        run: tar -czf ./MacOS.app.tar.gz -C ./build/macos/Build/Products/Release/spacehub.app .
        if: matrix.platform == 'macos-latest'
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./build/app/outputs/apk/release/app-armeabi-v7a-release.apk
            ./build/app/outputs/apk/release/app-arm64-v8a-release.apk
            ./build/app/outputs/apk/release/app-x86_64-release.apk
            ./Linux.tar.gz
            ./Windows.zip
            ./iOS.xcarchive.tar.gz
            ./MacOS.app.tar.gz