name: Release Package

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ windows-latest, macos-latest, ubuntu-latest ]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          override: true
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Install linux deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
        if: matrix.platform == 'ubuntu-latest'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.x
      - name: Install dependencies
        run: flutter pub get
      - name: Build APKs
        run: flutter build apk --split-per-abi
        if: matrix.platform == 'ubuntu-latest'
      - name: Build Linux
        run: flutter build linux
        if: matrix.platform == 'ubuntu-latest'
      - name: Gzip Linux build
        run: tar -czf ./build/linux/linux.tar.gz ./build/linux/release/
        if: matrix.platform == 'ubuntu-latest'
      - name: Build Windows
        run: flutter build windows
        if: matrix.platform == 'windows-latest'
      - name: Zip Windows build
        run: Compress-Archive -Path ./build/windows/runner/Release/ -DestinationPath ./build/windows/windows.zip
        if: matrix.platform == 'windows-latest'
      - name: Build iOS
        run: flutter build ipa
        if: matrix.platform == 'macos-latest'
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./build/app/outputs/apk/release/app-armeabi-v7a-release.apk
            ./build/app/outputs/apk/release/app-arm64-v8a-release.apk
            ./build/app/outputs/apk/release/app-x86_64-release.apk
            ./build/linux/linux.tar.gz
            ./build/windows/windows.zip
            ./build/ios/ipa/*.ipa
            ./build/ios/archive/*.xcarchive